---
version: 2.1
orbs: 
  bridgecrew: bridgecrew/bridgecrew@1.0.3
jobs: 
  build: 
    environment: 
      PRISMA_API_URL: "https://api.prismacloud.io"
    executor: bridgecrew/default
    steps: 
      - checkout
      - bridgecrew/scan: 
          api-key-variable: BC_API_KEY
          directory: "."